### ISSUE TITLE
io.UnsupportedOperation when running from CLI

### ISSUE THREAD

**Issue by pushfoo** [pypa/readme_renderer#298]
### Overview

Converting RST from the CLI breaks if run as follows:
```console
python -m readme_renderer ~/src/python-benedict/README.rst
```

Python versions tried: 3.9, 3.10, 3.12

#### Environment Info
| Software | Version / Comments |
|---|----|
| OS | Debian 11 |
| Python 3.9 | System default |
| Python 3.11 | Built from source |
| Python 3.12 | Built from source |

### Replication Steps

1. Install from source or `pip install readme_renderer`
2. `python -m readme_renderer README.rst` per the `--help` instructions
3. Observe the following (3.12 output below, exact formatting varies):
    ```
   <string>:297: (WARNING/2) Inline literal start-string without end-string.
   Traceback (most recent call last):
     File "<frozen runpy>", line 198, in _run_module_as_main
     File "<frozen runpy>", line 88, in _run_code
     File "/home/user/src/readme_renderer/readme_renderer/__main__.py", line 62, in <module>
       main()
     File "/home/user/src/readme_renderer/readme_renderer/__main__.py", line 50, in main
       rendered = render_rst(source, stream=sys.stderr)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/home/user/src/readme_renderer/readme_renderer/rst.py", line 133, in render
       if not stream.tell():
              ^^^^^^^^^^^^^
   io.UnsupportedOperation: underlying stream is not seekable
   ```

**Comment by miketheman** [comment]
I cannot reproduce this issue. Can you provide the RST source that is causing this error?

**Comment by miketheman** [comment]
Closing due to lack of response/

**Comment by domdfcoding** [comment]
I can reproduce with a completely empty file with the latest version on Python 3.12.

```bash
$ touch test.rst
$ python3 -m readme_renderer test.rst
venv/lib/python3.12/site-packages/readme_renderer/markdown.py:44: UserWarning: Markdown renderers are not available. Install 'readme_renderer[md]' to enable Markdown rendering.
  warnings.warn(_EXTRA_WARNING)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "venv/lib/python3.12/site-packages/readme_renderer/__main__.py", line 66, in <module>
    main()
  File "venv/lib/python3.12/site-packages/readme_renderer/__main__.py", line 50, in main
    rendered = render_rst(source, stream=sys.stderr)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/readme_renderer/rst.py", line 133, in render
    if not stream.tell():
           ^^^^^^^^^^^^^
io.UnsupportedOperation: underlying stream is not seekable
```

I thought it might be terminal specific (I was in VS Code's terminal) but it happens in Gnome Terminal too. I don't know if standard error will or should ever be seekable. The check for `stream.tell()` should be guarded with `stream.seekable()`
