### ISSUE TITLE
IndexError pop from empty list with some image links

### ISSUE THREAD

**Issue by Pawamoy** [pypa/readme_renderer#45]
Hi, today I encountered two times the same error (see below). It seems that some links like
`https://cloud.githubusercontent.com/assets/3999221/14685134/8cde04be-0733-11e6-8eda-b59f2e2fa6c3.png` are breaking stuff. Maybe it comes from a change on GitHub and not from readme_renderer because it was working well until now, with the same version.

Any ideas?

> Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    extras_require={
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/distutils/command/check.py", line 71, in run
    self.check_restructuredtext()
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/readme_renderer/integration/distutils.py", line 30, in check_restructuredtext
    markup = render(data, stream=stream)
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/readme_renderer/rst.py", line 115, in render
    parts = publish_parts(raw, writer=writer, settings_overrides=settings)
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/core.py", line 448, in publish_parts
    enable_exit_status=enable_exit_status)
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/writers/_html_base.py", line 71, in translate
    self.document.walkabout(visitor)
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/readme_renderer/rst.py", line 48, in depart_image
    self.body.append(self.context.pop())
IndexError: pop from empty list

**Comment by kdeldycke** [comment]
I concur. Have the same issue starting today, while a simple `$ ./setup.py check -m -r -s` has been working for a couple of weeks.

You can find a detailed traceback at: https://travis-ci.org/kdeldycke/meta-package-manager/jobs/182585925#L1283-L1322

**Comment by di** [comment]
I think #46 will fix this issue.

**Comment by di** [comment]
@Pawamoy, @kdeldycke, there's a new release of `readme_renderer` (16.0) which should fix this issue.

**Comment by kdeldycke** [comment]
Works perfectly now. Thanks for the insanely quick fix! 👍
