### ISSUE TITLE
linkify unexpected keyword argument 'skip_pre'  

### ISSUE THREAD

**Issue by Pawamoy** [pypa/readme_renderer#47]
Hi, I encountered this error today:

```
check runtests: commands[0] | python setup.py check --strict --metadata --restructuredtext
running check
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    extras_require={
  File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/distutils/command/check.py", line 71, in run
    self.check_restructuredtext()
  File "/media/pawamoy/Data/git/django-cs-models/.tox/check/lib/python3.5/site-packages/readme_renderer/integration/distutils.py", line 30, in check_restructuredtext
    markup = render(data, stream=stream)
  File "/media/pawamoy/Data/git/django-cs-models/.tox/check/lib/python3.5/site-packages/readme_renderer/rst.py", line 121, in render
    return clean(rendered)
  File "/media/pawamoy/Data/git/django-cs-models/.tox/check/lib/python3.5/site-packages/readme_renderer/clean.py", line 77, in clean
    parse_email=False,
TypeError: linkify() got an unexpected keyword argument 'skip_pre'
```

Here are the versions of the packages I'm using:

- check-manifest==0.35
- docutils==0.13.1
- readme-renderer==16.0
- Pygments==2.2.0

**Comment by di** [comment]
Hi @Pawamoy, can you let us know what version of `bleach` you were using as well?

**Comment by xavfernandez** [comment]
Hello, I'm getting the same error.
With `bleach==2.0.0` and https://travis-ci.org/Polyconseil/grocker/jobs/208984374#L507 for any other library :)

**Comment by di** [comment]
Looks like this changed in the latest release: https://github.com/mozilla/bleach/blob/b8b8e4aa9b688fb00f41959e74d8054e461f6aaf/CHANGES#L63-L77

**Comment by Pawamoy** [comment]
`bleach==2.0.0` too

**Comment by wfscheper** [comment]
Just curious what your release schedule/plans are. This is breaking several of my CI builds, and I want to know how much effort I should put into working around it vs just waiting for a fix.

Thanks!

**Comment by di** [comment]
@wfscheper Version 0.17 has been released: https://pypi.org/project/readme_renderer/17.0/

**Comment by SpotlightKid** [comment]
bleach 2.0.0 removes support for Python 2.6 but readme_renderer still states in the setup.py classifiers that it supports Python 2.6. Was it intentional to drop Python 2.6 support with the upgrade to bleach 2.0.0?
