### ISSUE TITLE
Improve text encoding error message

### ISSUE THREAD

**Issue by lgh2** [pypa/readme_renderer#70]
Since [the only character encoding that package metadata supports is UTF-8](https://packaging.python.org/specifications/core-metadata/?highlight=encoding#description-content-type-optional), I tried testing readme_renderer with a file in ISO/IEC 8859 encoding as the `long_description`. I got the following error message: 

```Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    long_description = f.read()
  File "/home/user/Python/Readme_GFM/venv/lib/python3.6/codecs.py", line 698, in read
    return self.reader.read(size)
  File "/home/user/Python/Readme_GFM/venv/lib/python3.6/codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte
```
I think it would be helpful to trap this exception in readme_renderer and give the user a more helpful error message that clearly indicates that their file is not in UTF-8 encoding.  I'm pretty confident I can do this for the case in which readme_renderer is invoked on the command line, but I am not sure how trapping and re-raising this error will affect the rest of Warehouse when it uses readme_renderer.

**Comment by lgh2** [comment]
Upon further investigation, I see that setuptools is kicking off this error.
